ALTER TABLE captains ADD COLUMN photo_focal_x REAL NOT NULL DEFAULT 50;
ALTER TABLE captains ADD COLUMN photo_focal_y REAL NOT NULL DEFAULT 30;
ALTER TABLE captains ADD COLUMN photo_zoom REAL NOT NULL DEFAULT 1;

ALTER TABLE media ADD COLUMN focal_x REAL NOT NULL DEFAULT 50;
ALTER TABLE media ADD COLUMN focal_y REAL NOT NULL DEFAULT 50;
ALTER TABLE media ADD COLUMN zoom REAL NOT NULL DEFAULT 1;
